### PR TITLE
Boris

### PR DESCRIPTION
**Pull request by jnicho02**
Run To The Hills

### CODE REVIEW

**Comment by zeripath** [comment]
You should probably add something about Farage quitting too.

**Comment by jnicho02** [comment]
Can do, but little bits at a time. I got to poke around with the grunt
build, which made me happy

**Comment by aranw** [comment]
@jnicho02 I think the following image would be better for Boris.

Might be able to find a bigger version with a bit of proper Googling. 

http://www.boriswatch.com/wp/wp-content/uploads/Boris-thumbs-up.jpg

**Comment by jnicho02** [comment]
Hi @aranw 

I think that the originator of the site wants to specifically use Creative Commons Licenced images. I've changed it for a shot of him on a bike. https://github.com/jnicho02/SinceWeVotedToLeaveTheEU/blob/master/img/backgrounds/boris-johnson.jpg Hope that is better.

It's not my site....so i'm still wondering whether Mr Applegate @qwghlm is going to accept my pull request
- Jez

**Comment by aranw** [comment]
@jnicho02 ah I didn't realise about the CC Licensing. Such a shame.

**Comment by qwghlm** [comment]
I'm going to close this PR without merging, as I don't think leadership shenanigans should be part of the site - who gets to be leader of a particular party is of concern to that party; while this site is focusing on the effect nationally and internationally. But thanks for the suggestion!

**Pull request closed without merging**
